import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import { Alert, Box, Button, Container, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material';
import BackButton from '@/components/BackButton';
import { Delete as DeleteIcon } from '@mui/icons-material';

interface MaleAnimal { id: string; earTag: string; name?: string; species: string; }
const emptyMaleForm = { earTag: '', name: '', species: 'CATTLE', breed: '', dateOfBirth: '' };

export default function BreedingPage() {
  const router = useRouter();
  const [records, setRecords] = useState<any[]>([]); const [error, setError] = useState('');
  const [males, setMales] = useState<MaleAnimal[]>([]); const [isMaleDialogOpen, setIsMaleDialogOpen] = useState(false); const [maleForm, setMaleForm] = useState(emptyMaleForm);
  const [form, setForm] = useState({ animalId: '', breedingType: 'ARTIFICIAL_INSEMINATION', dateOfBreeding: new Date().toISOString().slice(0, 10), technician: '', semen: '', sireId: '', notes: '' });
  const request = async (options: RequestInit = {}, id = '') => {
    const token = localStorage.getItem('token'); const user = JSON.parse(localStorage.getItem('user') || '{}');
    if (!token || !user.farmId) { router.push('/login'); throw new Error('Please log in again.'); }
    const response = await fetch(`/api/breeding?farmId=${encodeURIComponent(user.farmId)}${id ? `&id=${encodeURIComponent(id)}` : ''}`, { ...options, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', ...options.headers } });
    const body = await response.json(); if (!response.ok || !body.success) throw new Error(body.error || 'Request failed'); return body.data;
  };
  const load = async () => { try { setRecords(await request()); } catch (requestError: any) { setError(requestError.message); } };
  const loadMales = async () => { const token = localStorage.getItem('token'); const user = JSON.parse(localStorage.getItem('user') || '{}'); if (!token || !user.farmId) return; const response = await fetch(`/api/animals?farmId=${encodeURIComponent(user.farmId)}&pageSize=100`, { headers: { Authorization: `Bearer ${token}` } }); const body = await response.json(); if (response.ok && body.success && Array.isArray(body.data?.data)) setMales(body.data.data.filter((animal: MaleAnimal & { gender: string; status: string }) => animal.gender.toUpperCase() === 'MALE' && animal.status === 'ACTIVE')); };
  useEffect(() => { load(); loadMales(); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); try { await request({ method: 'POST', body: JSON.stringify(form) }); setForm({ ...form, animalId: '', technician: '', semen: '', sireId: '', notes: '' }); await load(); } catch (requestError: any) { setError(requestError.message); } };
  const addMale = async () => { setError(''); try { const token = localStorage.getItem('token'); const user = JSON.parse(localStorage.getItem('user') || '{}'); const response = await fetch(`/api/animals?farmId=${encodeURIComponent(user.farmId)}`, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ ...maleForm, gender: 'MALE', acquisitionDate: new Date().toISOString().slice(0, 10) }) }); const body = await response.json(); if (!response.ok || !body.success) throw new Error(body.error || 'Could not add male animal.'); setForm({ ...form, sireId: body.data.id }); setMaleForm(emptyMaleForm); setIsMaleDialogOpen(false); await loadMales(); } catch (requestError: any) { setError(requestError.message); } };
  const remove = async (id: string) => { if (!window.confirm('Delete this breeding record?')) return; try { await request({ method: 'DELETE' }, id); await load(); } catch (requestError: any) { setError(requestError.message); } };
  return <Container maxWidth="lg" sx={{ py: 4 }}><BackButton /><Typography variant="h4" gutterBottom>Breeding Management</Typography><Typography color="textSecondary" sx={{ mb: 3 }}>Record services and track expected birth dates.</Typography>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
    <Paper component="form" onSubmit={submit} sx={{ p: 3, mb: 3, display: 'grid', gap: 2, gridTemplateColumns: { md: 'repeat(3, 1fr)' } }}><TextField label="Animal ID or Ear Tag" required value={form.animalId} onChange={(event) => setForm({ ...form, animalId: event.target.value })} /><TextField select label="Breeding Type" value={form.breedingType} onChange={(event) => setForm({ ...form, breedingType: event.target.value, sireId: '' })}><MenuItem value="ARTIFICIAL_INSEMINATION">Artificial Insemination</MenuItem><MenuItem value="NATURAL_MATING">Natural Mating</MenuItem></TextField><TextField label="Breeding Date" type="date" required InputLabelProps={{ shrink: true }} value={form.dateOfBreeding} onChange={(event) => setForm({ ...form, dateOfBreeding: event.target.value })} />{form.breedingType === 'NATURAL_MATING' ? <Box display="flex" gap={1} alignItems="start"><TextField select required fullWidth label="Male Animal (Sire)" value={form.sireId} onChange={(event) => setForm({ ...form, sireId: event.target.value })}><MenuItem value="">Select male animal</MenuItem>{males.map((animal) => <MenuItem key={animal.id} value={animal.id}>{animal.earTag}{animal.name ? ` - ${animal.name}` : ''} ({animal.species})</MenuItem>)}</TextField><Button variant="outlined" onClick={() => setIsMaleDialogOpen(true)} sx={{ whiteSpace: 'nowrap', mt: 1 }}>Add Male</Button></Box> : <><TextField label="Technician" value={form.technician} onChange={(event) => setForm({ ...form, technician: event.target.value })} /><TextField label="Semen / Sire Details" value={form.semen} onChange={(event) => setForm({ ...form, semen: event.target.value })} /></>}<TextField label="Notes" value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /><Button type="submit" variant="contained">Save Breeding Record</Button></Paper>
    <TableContainer component={Paper}><Table><TableHead><TableRow><TableCell>Animal</TableCell><TableCell>Service Date</TableCell><TableCell>Expected Due Date</TableCell><TableCell>Type</TableCell><TableCell>Pregnancy Status</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{records.map((record) => <TableRow key={record.id}><TableCell>{record.animal?.name || record.animal?.earTag} ({record.animal?.earTag})</TableCell><TableCell>{new Date(record.dateOfBreeding).toLocaleDateString()}</TableCell><TableCell>{record.expectedCalving ? new Date(record.expectedCalving).toLocaleDateString() : '-'}</TableCell><TableCell>{record.breedingType.replace(/_/g, ' ')}</TableCell><TableCell>{record.pregnancyStatus.replace(/_/g, ' ')}</TableCell><TableCell align="right"><Button aria-label={`Delete breeding record ${record.id}`} color="error" onClick={() => remove(record.id)}><DeleteIcon /></Button></TableCell></TableRow>)}</TableBody></Table></TableContainer><Dialog open={isMaleDialogOpen} onClose={() => setIsMaleDialogOpen(false)} fullWidth maxWidth="xs"><DialogTitle>Add Male Animal</DialogTitle><DialogContent sx={{ display: 'grid', gap: 2, pt: '16px !important' }}><TextField autoFocus required label="Ear Tag" value={maleForm.earTag} onChange={(event) => setMaleForm({ ...maleForm, earTag: event.target.value })} /><TextField label="Name" value={maleForm.name} onChange={(event) => setMaleForm({ ...maleForm, name: event.target.value })} /><TextField select label="Species" value={maleForm.species} onChange={(event) => setMaleForm({ ...maleForm, species: event.target.value })}><MenuItem value="CATTLE">Cattle</MenuItem><MenuItem value="GOAT">Goat</MenuItem><MenuItem value="SHEEP">Sheep</MenuItem></TextField><TextField label="Breed" value={maleForm.breed} onChange={(event) => setMaleForm({ ...maleForm, breed: event.target.value })} /><TextField label="Date of Birth" type="date" InputLabelProps={{ shrink: true }} value={maleForm.dateOfBirth} onChange={(event) => setMaleForm({ ...maleForm, dateOfBirth: event.target.value })} /></DialogContent><DialogActions><Button onClick={() => setIsMaleDialogOpen(false)}>Cancel</Button><Button variant="contained" onClick={addMale} disabled={!maleForm.earTag}>Add and Select</Button></DialogActions></Dialog>
  </Container>;
}