import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import { Alert, Autocomplete, Box, Button, Checkbox, Chip, Container, MenuItem, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material';
import BackButton from '@/components/BackButton';
import { Delete as DeleteIcon } from '@mui/icons-material';

export default function TasksPage() {
  const router = useRouter();
  const [tasks, setTasks] = useState<any[]>([]); const [error, setError] = useState('');
  const [form, setForm] = useState({ title: '', description: '', reminderType: 'CUSTOM', dueDate: new Date().toISOString().slice(0, 10), priority: 'MEDIUM', assignedTo: '' });
  const request = async (options: RequestInit = {}, id = '') => {
    const token = localStorage.getItem('token'); const user = JSON.parse(localStorage.getItem('user') || '{}');
    if (!token || !user.farmId) { router.push('/login'); throw new Error('Please log in again.'); }
    const response = await fetch(`/api/tasks?farmId=${encodeURIComponent(user.farmId)}${id ? `&id=${encodeURIComponent(id)}` : ''}`, { ...options, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json', ...options.headers } });
    const body = await response.json(); if (!response.ok || !body.success) throw new Error(body.error || 'Request failed'); return body.data;
  };
  const load = async () => { try { setTasks(await request()); } catch (requestError: any) { setError(requestError.message); } };
  useEffect(() => { load(); }, []);
  const assigneeSuggestions = Array.from(new Set(tasks.map((task) => task.assignedTo).filter((name): name is string => Boolean(name))));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); try { await request({ method: 'POST', body: JSON.stringify(form) }); setForm({ ...form, title: '', description: '', assignedTo: '' }); await load(); } catch (requestError: any) { setError(requestError.message); } };
  const toggle = async (task: any) => { try { await request({ method: 'PUT', body: JSON.stringify({ completed: !task.completed }) }, task.id); await load(); } catch (requestError: any) { setError(requestError.message); } };
  const remove = async (task: any) => { if (!window.confirm(`Delete task "${task.title}"?`)) return; try { await request({ method: 'DELETE' }, task.id); await load(); } catch (requestError: any) { setError(requestError.message); } };
  return <Container maxWidth="lg" sx={{ py: 4 }}><BackButton /><Typography variant="h4" gutterBottom>Farm Tasks</Typography><Typography color="textSecondary" sx={{ mb: 3 }}>Plan work, set due dates, and track completion.</Typography>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
    <Paper component="form" onSubmit={submit} sx={{ p: 3, mb: 3, display: 'grid', gap: 2, gridTemplateColumns: { md: 'repeat(3, 1fr)' } }}><TextField label="Task" required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /><TextField label="Details" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /><TextField label="Due Date" type="date" required InputLabelProps={{ shrink: true }} value={form.dueDate} onChange={(event) => setForm({ ...form, dueDate: event.target.value })} /><TextField select label="Category" value={form.reminderType} onChange={(event) => setForm({ ...form, reminderType: event.target.value })}><MenuItem value="CUSTOM">General Task</MenuItem><MenuItem value="MILKING">Milking</MenuItem><MenuItem value="MAINTENANCE">Maintenance</MenuItem><MenuItem value="VACCINATION">Vaccination</MenuItem><MenuItem value="INVENTORY_LOW">Inventory</MenuItem></TextField><TextField select label="Priority" value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value })}><MenuItem value="LOW">Low</MenuItem><MenuItem value="MEDIUM">Medium</MenuItem><MenuItem value="HIGH">High</MenuItem></TextField><Autocomplete freeSolo options={assigneeSuggestions} value={form.assignedTo} inputValue={form.assignedTo} onChange={(_event, value) => setForm({ ...form, assignedTo: value || '' })} onInputChange={(_event, value, reason) => { if (reason !== 'reset') setForm({ ...form, assignedTo: value }); }} renderInput={(params) => <TextField {...params} label="Assigned To" placeholder="e.g. John Doe" />} /><Button type="submit" variant="contained">Add Task</Button></Paper>
    <TableContainer component={Paper}><Table><TableHead><TableRow><TableCell>Done</TableCell><TableCell>Task</TableCell><TableCell>Due</TableCell><TableCell>Category</TableCell><TableCell>Priority</TableCell><TableCell>Assigned To</TableCell><TableCell>Status</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{tasks.map((task) => <TableRow key={task.id} sx={{ opacity: task.completed ? 0.55 : 1 }}><TableCell><Checkbox aria-label={`Mark ${task.title} complete`} checked={task.completed} onChange={() => toggle(task)} /></TableCell><TableCell>{task.title}<Typography variant="body2" color="textSecondary">{task.description}</Typography></TableCell><TableCell>{new Date(task.dueDate).toLocaleDateString()}</TableCell><TableCell>{task.reminderType.replace(/_/g, ' ')}</TableCell><TableCell>{task.priority}</TableCell><TableCell>{task.assignedTo || '—'}</TableCell><TableCell><Chip size="small" label={task.completed ? 'Completed' : new Date(task.dueDate) < new Date() ? 'Overdue' : 'Pending'} color={task.completed ? 'success' : new Date(task.dueDate) < new Date() ? 'error' : 'default'} /></TableCell><TableCell align="right"><Button aria-label={`Delete task ${task.id}`} color="error" onClick={() => remove(task)}><DeleteIcon /></Button></TableCell></TableRow>)}</TableBody></Table></TableContainer>
  </Container>;
}